version: '3.8'

services:
  ec_prayer_times-app:
    image: abdulrahmanhadz/ec_prayer_times:v0.0.2
    ports:
      - "5164:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
